/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.clubdesurf;

/**
 *
 * @author luis
 */
public class AtualizarDadosSocioUI extends javax.swing.JFrame {
    private static Aluno alt;

    /**
     * Creates new form AtualizarDadosSocio
     */
    public AtualizarDadosSocioUI() {
        initComponents();
    }
    
    public AtualizarDadosSocioUI(Aluno a) {
        alt = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancelar_button = new javax.swing.JButton();
        updCurso_text = new javax.swing.JTextField();
        updEmail_text = new javax.swing.JTextField();
        updMorada_text = new javax.swing.JTextField();
        mudar_curso = new javax.swing.JButton();
        mudar_email = new javax.swing.JButton();
        mudar_morada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        jLabel2.setText("Atualizar Dados");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 40, 330, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/luis/NetBeansProjects/JavaApplication4/images/a-imagem-de-russell-b-que-encantou-o-mundo.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 120);

        jLabel4.setText("Curso:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 200, 52, 23);

        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 290, 57, 23);

        jLabel6.setText("Morada:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 380, 67, 23);

        cancelar_button.setText("Cancelar");
        cancelar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar_button);
        cancelar_button.setBounds(320, 470, 130, 37);
        jPanel1.add(updCurso_text);
        updCurso_text.setBounds(80, 190, 390, 33);
        jPanel1.add(updEmail_text);
        updEmail_text.setBounds(80, 280, 390, 33);
        jPanel1.add(updMorada_text);
        updMorada_text.setBounds(80, 370, 390, 33);

        mudar_curso.setText("Mudar");
        mudar_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudar_cursoActionPerformed(evt);
            }
        });
        jPanel1.add(mudar_curso);
        mudar_curso.setBounds(470, 190, 90, 37);

        mudar_email.setText("Mudar");
        mudar_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudar_emailActionPerformed(evt);
            }
        });
        jPanel1.add(mudar_email);
        mudar_email.setBounds(470, 280, 90, 37);

        mudar_morada.setText("Mudar");
        mudar_morada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudar_moradaActionPerformed(evt);
            }
        });
        jPanel1.add(mudar_morada);
        mudar_morada.setBounds(470, 370, 90, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_buttonActionPerformed
            // TODO add your handling code here:
            this.dispose();
    }//GEN-LAST:event_cancelar_buttonActionPerformed

    private void dadosMudadosSuc(){
        javax.swing.JOptionPane.showMessageDialog(this, "Dados Mudados com Sucesso", "Message", -1);
    }
    
    private void mudar_moradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudar_moradaActionPerformed
        if(!this.updMorada_text.getText().equals("")){
            alt.setMorada(this.updMorada_text.getText());
            dadosMudadosSuc();
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Campo vazio!!", "Message", 0);
        }
    }//GEN-LAST:event_mudar_moradaActionPerformed

    private void mudar_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudar_cursoActionPerformed
        // TODO add your handling code here:
        if(!this.updCurso_text.getText().equals("")){
            alt.setCurso(this.updCurso_text.getText());
            dadosMudadosSuc();
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Campo vazio!!", "Message", 0);
        }
    }//GEN-LAST:event_mudar_cursoActionPerformed

    private void mudar_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudar_emailActionPerformed
        // TODO add your handling code here:
        if(!this.updEmail_text.getText().equals("")){
            alt.setEmail(this.updEmail_text.getText());
            dadosMudadosSuc();
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Campo vazio!!", "Message", 0);
        }
    }//GEN-LAST:event_mudar_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarDadosSocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarDadosSocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarDadosSocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarDadosSocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarDadosSocioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mudar_curso;
    private javax.swing.JButton mudar_email;
    private javax.swing.JButton mudar_morada;
    private javax.swing.JTextField updCurso_text;
    private javax.swing.JTextField updEmail_text;
    private javax.swing.JTextField updMorada_text;
    // End of variables declaration//GEN-END:variables
}
