/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.clubdesurf;

import java.io.IOException;

/**
 *
 * @author luis
 */
public class ListaDeMembrosUI extends javax.swing.JFrame {
    
    public static Clube club;
    /**
     * Creates new form ListaDeMembros
     */
    public ListaDeMembrosUI() {
        try {            
                    club = Clube.leObj("clubedesurf.txt"); 
                } 
                catch (IOException e) {
                    club = new Clube();
                    System.out.println("Não foi possível ler os dados!\nErro de leitura.");
                }
                catch (ClassNotFoundException e) { 
                    club = new Clube();
                    System.out.println("Não foi possível ler os dados!\nFicheiro com formato desconhecido.");
                }
                catch(ClassCastException e) {
                    club = new Clube();
                    System.out.println("Não foi possível ler os dados!\nFicheiro com formato errado.");
                }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ver_socios = new javax.swing.JButton();
        add_socio = new javax.swing.JButton();
        pesquisar_text = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        remove_socio = new javax.swing.JButton();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 50, 170, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/luis/NetBeansProjects/JavaApplication4/images/a-imagem-de-russell-b-que-encantou-o-mundo.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 880, 160);

        ver_socios.setText("Ver Sócios");
        ver_socios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_Socios_ActionPerformed(evt);
            }
        });
        jPanel1.add(ver_socios);
        ver_socios.setBounds(360, 330, 110, 37);

        add_socio.setText("Adicionar Sócio");
        add_socio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_socioActionPerformed(evt);
            }
        });
        jPanel1.add(add_socio);
        add_socio.setBounds(330, 420, 170, 37);

        pesquisar_text.setText("nº de sócio");
        jPanel1.add(pesquisar_text);
        pesquisar_text.setBounds(290, 190, 240, 33);

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(pesquisar);
        pesquisar.setBounds(260, 240, 130, 37);

        remove_socio.setText("Remover");
        remove_socio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_socioActionPerformed(evt);
            }
        });
        jPanel1.add(remove_socio);
        remove_socio.setBounds(440, 240, 130, 37);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel1.add(sair);
        sair.setBounds(630, 490, 110, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ver_Socios_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_Socios_ActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JOptionPane.showMessageDialog(this, club.toString(), "Lista de sócios", -1);
       
    }//GEN-LAST:event_Ver_Socios_ActionPerformed
    
    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:
        
        if (!this.pesquisar_text.getText().equals("") && 
                club.existe(Integer.parseInt(this.pesquisar_text.getText()))){
            Menu_SocioUI menu_socio = new Menu_SocioUI(club.getAluno(Integer.parseInt(this.pesquisar_text.getText())));
            menu_socio.setVisible(true);
        }
        else javax.swing.JOptionPane.showMessageDialog(this, "Sócio não existe!!", "Message", 0);
        
    }//GEN-LAST:event_pesquisarActionPerformed

    private void remove_socioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_socioActionPerformed
        // TODO add your handling code here:
        if(!this.pesquisar_text.getText().equals("") && 
                club.existe(Integer.parseInt(this.pesquisar_text.getText()))){
            club.removerAluno(Integer.parseInt(this.pesquisar_text.getText()));
            javax.swing.JOptionPane.showMessageDialog(this, "Acabou de eliminar o associado "
                    + Integer.parseInt(this.pesquisar_text.getText()), "Message", -1);
        }
        else javax.swing.JOptionPane.showMessageDialog(this, "Sócio não existe!!", "Message", 0);
    }//GEN-LAST:event_remove_socioActionPerformed

    private void add_socioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_socioActionPerformed
        // TODO add your handling code here:
        PaginaDeDadosUI addsocio = new  PaginaDeDadosUI();
        addsocio.setVisible(true);
    }//GEN-LAST:event_add_socioActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        try { 
            club.gravaObj("clubedesurf.txt"); 
        }
        catch (IOException e) {  
            System.out.println("Não consegui gravar os dados!");
        }
        this.dispose();
        ClubDeSurfUI clubdesurf = new ClubDeSurfUI();
        clubdesurf.setVisible(true);
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeMembrosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeMembrosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeMembrosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeMembrosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new ListaDeMembrosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_socio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField pesquisar_text;
    private javax.swing.JButton remove_socio;
    private javax.swing.JButton sair;
    private javax.swing.JButton ver_socios;
    // End of variables declaration//GEN-END:variables
}
