/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.clubdesurf;

/**
 *
 * @author luis
 */
public class Menu_SocioUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Socio
     */
    public Menu_SocioUI() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ver_dados = new javax.swing.JButton();
        ver_cotas = new javax.swing.JButton();
        sair_associado = new javax.swing.JButton();
        atualizar_dados = new javax.swing.JButton();
        pagar_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        jLabel2.setText("Menu do Associado");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 50, 390, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/luis/NetBeansProjects/JavaApplication4/images/a-imagem-de-russell-b-que-encantou-o-mundo.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 140);

        ver_dados.setText("Ver Dados");
        ver_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_dadosActionPerformed(evt);
            }
        });
        jPanel1.add(ver_dados);
        ver_dados.setBounds(340, 170, 130, 50);

        ver_cotas.setText("Ver Cotas");
        ver_cotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_cotasActionPerformed(evt);
            }
        });
        jPanel1.add(ver_cotas);
        ver_cotas.setBounds(340, 340, 130, 50);

        sair_associado.setText("Sair");
        sair_associado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_associadoActionPerformed(evt);
            }
        });
        jPanel1.add(sair_associado);
        sair_associado.setBounds(680, 470, 110, 37);

        atualizar_dados.setText("Atualizar Dados");
        atualizar_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_dadosActionPerformed(evt);
            }
        });
        jPanel1.add(atualizar_dados);
        atualizar_dados.setBounds(310, 260, 180, 37);

        pagar_button.setText("Pagar Cotas");
        pagar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagar_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(pagar_button);
        pagar_button.setBounds(340, 430, 130, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ver_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_dadosActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Dados do User...etc", "Dados", -1);
    }//GEN-LAST:event_ver_dadosActionPerformed

    private void ver_cotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_cotasActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Cotas de utilizador...etc", "Dados", -1);
    }//GEN-LAST:event_ver_cotasActionPerformed

    private void sair_associadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_associadoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_sair_associadoActionPerformed

    private void atualizar_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar_dadosActionPerformed
        // TODO add your handling code here:
        AtualizarDadosSocioUI atualizar = new AtualizarDadosSocioUI();
        atualizar.setVisible(true);
    }//GEN-LAST:event_atualizar_dadosActionPerformed

    private void pagar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagar_buttonActionPerformed
        // TODO add your handling code here:
        PagarCotasUI pagar = new PagarCotasUI();
        pagar.setVisible(true); 
    }//GEN-LAST:event_pagar_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_SocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_SocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_SocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_SocioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_SocioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar_dados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pagar_button;
    private javax.swing.JButton sair_associado;
    private javax.swing.JButton ver_cotas;
    private javax.swing.JButton ver_dados;
    // End of variables declaration//GEN-END:variables
}
