/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.clubdesurf;

/**
 *
 * @author luis
 */
public class PagarCotasUI extends javax.swing.JFrame {

    /**
     * Creates new form PagarCotas
     */
    public PagarCotasUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dia_text = new javax.swing.JTextField();
        mes_text = new javax.swing.JTextField();
        ano_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        valor_text = new javax.swing.JTextField();
        pagar_button = new javax.swing.JButton();
        cancelar_pay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        jLabel2.setText("Dados da Cota");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 50, 270, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/luis/NetBeansProjects/JavaApplication4/images/a-imagem-de-russell-b-que-encantou-o-mundo.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 130);

        jLabel3.setText("Dia:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 180, 57, 23);

        jLabel4.setText("Ano:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 180, 37, 23);

        jLabel5.setText("Mês:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 180, 38, 23);
        jPanel1.add(dia_text);
        dia_text.setBounds(50, 170, 130, 33);
        jPanel1.add(mes_text);
        mes_text.setBounds(240, 170, 150, 33);
        jPanel1.add(ano_text);
        ano_text.setBounds(440, 170, 150, 33);

        jLabel6.setText("Valor:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 270, 57, 23);
        jPanel1.add(valor_text);
        valor_text.setBounds(70, 260, 170, 33);

        pagar_button.setText("Confirmar");
        pagar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagar_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(pagar_button);
        pagar_button.setBounds(190, 470, 110, 37);

        cancelar_pay.setText("Cancelar");
        cancelar_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_payActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar_pay);
        cancelar_pay.setBounds(440, 470, 120, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_payActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelar_payActionPerformed

    private void pagar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagar_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagar_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarCotasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarCotasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarCotasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarCotasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarCotasUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano_text;
    private javax.swing.JButton cancelar_pay;
    private javax.swing.JTextField dia_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mes_text;
    private javax.swing.JButton pagar_button;
    private javax.swing.JTextField valor_text;
    // End of variables declaration//GEN-END:variables
}
