/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.clubdesurf;

/**
 *
 * @author luis
 */
public class PaginaDeDadosUI extends javax.swing.JFrame {

    /**
     * Creates new form PaginaDeDados
     */
    public PaginaDeDadosUI(Clube club) {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        num_text = new javax.swing.JTextField();
        ano_text = new javax.swing.JTextField();
        curso_text = new javax.swing.JTextField();
        morada_text = new javax.swing.JTextField();
        email_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        jLabel1.setText("Criar Conta");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 60, 280, 50);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 200, 70, 24);

        nome_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_textActionPerformed(evt);
            }
        });
        jPanel1.add(nome_text);
        nome_text.setBounds(120, 200, 230, 33);

        jLabel4.setText("Número:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 200, 80, 23);

        jLabel5.setText("Ano:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 270, 50, 23);

        jLabel6.setText("Curso:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(430, 270, 57, 23);

        jLabel7.setText("Morada:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 340, 80, 23);

        jLabel8.setText("Email:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 340, 57, 23);
        jPanel1.add(num_text);
        num_text.setBounds(490, 200, 70, 33);
        jPanel1.add(ano_text);
        ano_text.setBounds(120, 270, 80, 33);
        jPanel1.add(curso_text);
        curso_text.setBounds(490, 260, 240, 33);
        jPanel1.add(morada_text);
        morada_text.setBounds(120, 340, 300, 33);
        jPanel1.add(email_text);
        email_text.setBounds(490, 340, 300, 33);

        jButton1.setText("Criar Conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarConta_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 420, 120, 37);

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/luis/NetBeansProjects/JavaApplication4/images/a-imagem-de-russell-b-que-encantou-o-mundo.jpg")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 820, 150);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar);
        cancelar.setBounds(460, 420, 140, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean dadosValidos() {
        boolean valido = this.nome_text.getText().equals("") || this.num_text.getText().equals("") 
                         || this.ano_text.getText().equals("") || this.curso_text.getText().equals("")
                         || this.morada_text.getText().equals("") || this.email_text.getText().equals("");
        
        if (valido)
            javax.swing.JOptionPane.showMessageDialog(this, "Todos os campos são de preenchimento obrigatório!!", "Message", 0);
        
        return !valido;
    }
    
    private void CriarConta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarConta_ActionPerformed
        // TODO add your handling code here:
        if (this.dadosValidos()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Conta criada com sucesso.", "Message", -1);
            this.setDefaultCloseOperation(3);
            this.dispose();
        } 
    }//GEN-LAST:event_CriarConta_ActionPerformed

    private void nome_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_textActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaDeDadosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaDeDadosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaDeDadosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaDeDadosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaDeDadosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano_text;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField curso_text;
    private javax.swing.JTextField email_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField morada_text;
    private javax.swing.JTextField nome_text;
    private javax.swing.JTextField num_text;
    // End of variables declaration//GEN-END:variables
}
